platform :ios, '8.0'

target 'XTGoHome' do

#网络请求
pod 'AFNetworking', '~> 3.1.0'
#图片缓存
pod 'SDWebImage', '~>3.8'
#AutoLayout
pod 'Masonry'
#字典转模型
pod 'MJExtension', '~> 3.0.13'
#HUD
pod 'MBProgressHUD', '~> 1.0.0'
#刷新控件
pod 'MJRefresh', '~> 3.1.12'
#图片轮播
pod 'SDCycleScrollView'
#播放器
pod 'ZFPlayer'
pod 'ZFDownload'
pod 'MWPhotoBrowser'
end
